# Sidebar navigation

- label: 'What is use pandas?'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Working with CSVs
  items:
    - label: 'Append csv files'
      link: '/csv/append-csv-files'

- label: Community
  items:
    - label: 'Github'
      link: https://github.com/kennethcassel/usepandas
    - label: 'Twitter'
      link: https://twitter.com/KennethCassel
